### ISSUE TITLE
Completely missing unit tests

### ISSUE THREAD

**Issue by ewoks** [aurasphere/blue-pair#7]
Unit tests would contribute a lot to overall quality of project

**Comment by aurasphere** [comment]
Hi ewoks! Thank you for your contribution! I agree with you, unit tests will improve overall quality. The problem is that the app is strongly dependent on other devices since it's about bluetooth pairing. If you have any suggestions for tests to implement or you want to add them yourself, feel free to suggest/help. Thank you again!

**Comment by vrnsky** [comment]
@aurasphere Hi, I am new for your project I see code and my suggestion is used mockito and powermockito with junit to testing. Mockito provide mocking function and power mockito allow check that some method called in class. For example:
``` 
Context context = mock(Context.class);
BluetoothDiscoveryDeviceListener listener = mock(BluetoothDiscoveryDeviceListener.class);

BluetoothController controller = new BluetoothController(context, listener);

when(controller.isBluetoothEnabled()).thenReturn(false);
assertThat(controller.isBluetoothEnabled(), is(false));
```
